/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "./common";

export type ERC1155DataStruct = { name: string; symbol: string; kya: string };

export type ERC1155DataStructOutput = [string, string, string] & {
  name: string;
  symbol: string;
  kya: string;
};

export interface SX1155NFTFactoryInterface extends utils.Interface {
  functions: {
    "deployChainWiki((string,string,string),address,address)": FunctionFragment;
  };

  getFunction(nameOrSignatureOrTopic: "deployChainWiki"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "deployChainWiki",
    values: [ERC1155DataStruct, string, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "deployChainWiki",
    data: BytesLike
  ): Result;

  events: {
    "ChainWikiDeployed(address,(string,string,string),address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "ChainWikiDeployed"): EventFragment;
}

export interface ChainWikiDeployedEventObject {
  deployedAddress: string;
  tokenParams: ERC1155DataStructOutput;
  admin: string;
  editor: string;
}
export type ChainWikiDeployedEvent = TypedEvent<
  [string, ERC1155DataStructOutput, string, string],
  ChainWikiDeployedEventObject
>;

export type ChainWikiDeployedEventFilter =
  TypedEventFilter<ChainWikiDeployedEvent>;

export interface SX1155NFTFactory extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: SX1155NFTFactoryInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    deployChainWiki(
      tokenParams: ERC1155DataStruct,
      _admin: string,
      _editor: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;
  };

  deployChainWiki(
    tokenParams: ERC1155DataStruct,
    _admin: string,
    _editor: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  callStatic: {
    deployChainWiki(
      tokenParams: ERC1155DataStruct,
      _admin: string,
      _editor: string,
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {
    "ChainWikiDeployed(address,(string,string,string),address,address)"(
      deployedAddress?: null,
      tokenParams?: null,
      admin?: null,
      editor?: null
    ): ChainWikiDeployedEventFilter;
    ChainWikiDeployed(
      deployedAddress?: null,
      tokenParams?: null,
      admin?: null,
      editor?: null
    ): ChainWikiDeployedEventFilter;
  };

  estimateGas: {
    deployChainWiki(
      tokenParams: ERC1155DataStruct,
      _admin: string,
      _editor: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    deployChainWiki(
      tokenParams: ERC1155DataStruct,
      _admin: string,
      _editor: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;
  };
}
