image:
  repository: ""  
  pullPolicy: Always


service:
  port: 80

ingress:
  enabled: true
  host: app.chainwiki.com 

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: "chainwiki"
              operator: In
              values:
                - "enabled"

tolerations:
  - key: "chainwiki"
    operator: "Equal"
    value: "true"
    effect: "NoSchedule"

nodeSelector:
  chainwiki: "enabled"
