/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  SX1155NFTFactory,
  SX1155NFTFactoryInterface,
} from "../SX1155NFTFactory";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "contract ChainWiki",
        name: "deployedAddress",
        type: "address",
      },
      {
        components: [
          {
            internalType: "string",
            name: "name",
            type: "string",
          },
          {
            internalType: "string",
            name: "symbol",
            type: "string",
          },
          {
            internalType: "string",
            name: "kya",
            type: "string",
          },
        ],
        indexed: false,
        internalType: "struct ERC1155Data",
        name: "tokenParams",
        type: "tuple",
      },
      {
        indexed: false,
        internalType: "address",
        name: "admin",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "editor",
        type: "address",
      },
    ],
    name: "ChainWikiDeployed",
    type: "event",
  },
  {
    inputs: [
      {
        components: [
          {
            internalType: "string",
            name: "name",
            type: "string",
          },
          {
            internalType: "string",
            name: "symbol",
            type: "string",
          },
          {
            internalType: "string",
            name: "kya",
            type: "string",
          },
        ],
        internalType: "struct ERC1155Data",
        name: "tokenParams",
        type: "tuple",
      },
      {
        internalType: "address",
        name: "_admin",
        type: "address",
      },
      {
        internalType: "address",
        name: "_editor",
        type: "address",
      },
    ],
    name: "deployChainWiki",
    outputs: [
      {
        internalType: "contract ChainWiki",
        name: "newSx1155",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class SX1155NFTFactory__factory {
  static readonly abi = _abi;
  static createInterface(): SX1155NFTFactoryInterface {
    return new utils.Interface(_abi) as SX1155NFTFactoryInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): SX1155NFTFactory {
    return new Contract(address, _abi, signerOrProvider) as SX1155NFTFactory;
  }
}
